### ISSUE TITLE
Querying GeoJSON data using Eve v0.7.6 does not work.

### ISSUE THREAD

**Issue by abchang1** [pyeve/eve#1103]
Hello,

I’m using Eve v0.7.6  and MongoDB v3.0.6, and followed the instruction to query GeoJSON data on the Eve document, http://python-eve.org/features#geojson.
I tested the following GeoJSON query as shown in the instruction using Postman:

http://localhost:5000/people?where={"location": {"$near": {"$geometry": {"type":"Point", "coordinates": [10.0, 20.0]}, "$maxDistance": 1000}}}

However, the following error message was returned:
{
    "_status": "ERR",
    "_error": {
        "message": "The browser (or proxy) sent a request that this server could not understand.",
        "code": 400
    }
}

I created ‘people’ collection and a 2dsphere index on ‘location’ field as shown bellow:
    {
        "v" : 1,
        "key" : {
            "location" : "2dsphere"
        },
        "name" : "location_2dsphere",
        "ns" : "eve.people",
        "2dsphereIndexVersion" : 2
    }

The people collection has the following document:
/* 1 */
{
    "_id" : ObjectId("5a67601083cfbe38f33ecd31"),
    "_updated" : ISODate("2018-01-23T16:17:20.000Z"),
    "firstname" : "barack",
    "lastname" : "obama",
    "location" : {
        "type" : "Point",
        "coordinates" : [ 
            100.0, 
            10.0
        ]
    },
    "_created" : ISODate("2018-01-23T16:17:20.000Z"),
    "_etag" : "753efbcc0a062c034f9efab30cd05e9a4cd9d24c"
}

settings.py has the definitions of people and domain as shown below:
#people definition 
people = {
    'item_title': 'person',

    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'lastname'
    },

    'cache_control': 'max-age=10,must-revalidate',
    'cache_expires': 10,

    'resource_methods': ['GET', 'POST'],

    'schema': {
        'firstname': {
            'type': 'string',
            'minlength': 1,
            'maxlength': 10,
        },
        'lastname': {
            'type': 'string',
            'minlength': 1,
            'maxlength': 15,
            'required': True,
            'unique': True,
        },
        # 'role' is a list, and can only contain values from 'allowed'.
        'role': {
            'type': 'list',
            'allowed': ["author", "contributor", "copy"],
        },
        # An embedded 'strongly-typed' dictionary.
        'location': {
            'type': 'point'
        },
        'born': {
            'type': 'datetime',
        },
    }
}

#domain definition
DOMAIN = {'people': people
        }

Please look into this issue.

**Comment by ajk3e** [comment]
I am having a very similar experience trying to get the example running with a geospatial query.  When I hit the endpoint:

`http://localhost:5000/people?where={"location": {"$near": {"$geometry": {"type":"Point", "coordinates": [10.0, 20.0]}, "$maxDistance": 1000}}}`

I get the response:

`{
    "_status": "ERR",
    "_error": {
        "message": "Query contains unknown or unsupported operators: $geometry, $maxDistance",
        "code": 400
    }
}`

I have a spatial index set up on my people collection:

`{
    "location" : "2dsphere"
}`

I'm running Eve v0.7.6, Python 2.7.13, and MongoDB v3.6.1.  I have attached a .zip containing 
[eve_geospatial.zip](https://github.com/pyeve/eve/files/1693056/eve_geospatial.zip)
my settings.py and app.py.

**Comment by nicolaiarocci** [comment]
Hi guys, could you please let me know if things get back to normal when working with an Eve version prior to 0.7.6?

**Comment by nicolaiarocci** [comment]
Nevermind that. I pushed a potential fix to [this](https://github.com/pyeve/eve/tree/fix_geo_queries_%231103) branch. Could you please report back know if that actually works on your side?

**Comment by abchang1** [comment]
Thanks for working on this issue.
I tested the query with the development version of Eve, but I still get 400 error.
{
    "_status": "ERR",
    "_error": {
        "message": "The browser (or proxy) sent the same geospatial request that this server could not understand.",
        "code": 400
    }
}

The following is the python modules on my virtualenv.

$ venv/bin/pip freeze
Cerberus==1.1
click==6.7
Eve==0.8.dev0
Events==0.3
Flask==0.12
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==0.23
pymongo==3.6.0
simplejson==3.13.2
Werkzeug==0.11.15
wheel==0.24.0

**Comment by nicolaiarocci** [comment]
@abchang1 did you test the master branch, or the branch I linked in the previous comment? Master has no fixes for this issue.

**Comment by abchang1** [comment]
Sorry that I used the master branch.  
I tested the geospatial query using fix_geo_queries_#1103 branch, and it works.
Thank you for fixing the bug and hope that new lease with the fix will come soon.

**Comment by nicolaiarocci** [comment]
v0.7.7 has been released with a fix for this issue.

**Comment by abchang1** [comment]
Thanks!

**Comment by waliddamou** [comment]
still the same issue
