### ISSUE TITLE
Cannot query document reference in subdocument.

### ISSUE THREAD

**Issue by jwfuller** [pyeve/eve#998]
I have the following resource defined:

```python
item = {
    'wrapper': {
        'type': 'dict',
        'schema': {
            'element': {
                'type': 'objectid',
                'data_relation': {
                 'resource': 'code',
                 'field': '_id',
                     'embeddable': True,
                 },
            },
        },
    },
}

```
When I try to query using the objectid, I get empty list.

`http://127.0.0.1:5000/item?where={"wrapper.element":"5834987589b0dc353b72c27d"}`

`5834987589b0dc353b72c27d` is the valid _id for the element.

If I move the data relation out of the subdocument I can query it as expected.

**Comment by pointtoken** [comment]
Did you ever solve this? I can't seem to query inside sub documents...

**Comment by jwfuller** [comment]
I think this was resolved in v0.7.3. It is no longer an issue for me. If @pointtoken could test, that would be great

**Comment by pointtoken** [comment]
I'm running 0.7.5 and it is still broken. My scenario is slightly different though:.  I have an array of sub documents, aka 
`{
    "buyers" : [ 
        {
            "id" : 12,
            "amount" : 2
        }, 
        {
            "id" : 14,
            "amount" : 3
        }
    ]
}`

and I want to query it like:
`find({"buyers.id":{$eq:12}})`

Is this expected to work? It blows up bigtime.

**Comment by jwfuller** [comment]
I don't think query for a value inside the embedded doc is supported

**Comment by nicolaiarocci** [comment]
>  don't think query for a value inside the embedded doc is supported

Right.
